repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
  - repo: https://github.com/AleksaC/hadolint-py
    rev: v2.14.0
    hooks:
      - id: hadolint
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.48.0
    hooks:
      - id: markdownlint
  - repo: https://github.com/mrtazz/checkmake
    rev: v0.3.2
    hooks:
      - id: checkmake
